#!/bin/bash

LOCALDIR=`cd "$( dirname ${BASH_SOURCE[0]} )" && pwd`
cd $LOCALDIR

systemdir=$1

rm -rf $1/data-app/*
rm -rf $1/priv-app/MIUIAod
rm -rf $1/priv-app/MIUIBrowser
rm -rf $1/priv-app/MIUICamera
rm -rf $1/priv-app/MIUIContentExtension
rm -rf $1/priv-app/MIUIMusic
rm -rf $1/priv-app/MIUIVideo
rm -rf $1/priv-app/MIUIGallery
rm -rf $1/priv-app/Mirror
rm -rf $1/priv-app/MIUIShare
rm -rf $1/priv-app/MIUICalendar
rm -rf $1/priv-app/MIUIYellowPage
rm -rf $1/app/MiLink
rm -rf $1/app/MILink
rm -rf $1/app/MIPay
rm -rf $1/app/mab
rm -rf $1/app/MiSound  
rm -rf $1/app/MIUIDeskClock
rm -rf $1/app/MIUIFileExplorer 
rm -rf $1/app/MIUISuperMarket 
rm -rf $1/product/data-app/*
rm -rf $1/product/app/TrichromeLibrary
rm -rf $1/product/media/audio/alarms/*
rm -rf $1/product/media/audio/notifications/*
rm -rf $1/product/media/audio/ringtones/*
rm -rf $1/*app/*eibo*
# Nuke MIUI useless system apks
rm -rf $1/app/cit
rm -rf $1/app/MiuiCompass
rm -rf $1/app/MiuiVideoGlobal
rm -rf $1/app/PaymentService
rm -rf $1/app/Calculator
rm -rf $1/app/VoiceAssist
rm -rf $1/app/MiRadio
rm -rf $1/app/Mipay
rm -rf $1/app/NextPay
rm -rf $1/app/com.miui.qr
rm -rf $1/app/MiuiBugReport
rm -rf $1/app/AnalyticsCore
rm -rf $1/app/BasicDreams
rm -rf $1/app/BugReport
rm -rf $1/app/Drive
rm -rf $1/app/Duo
rm -rf $1/app/Gmail2
rm -rf $1/app/HybridAccessory
rm -rf $1/app/HybridPlatform
rm -rf $1/app/InMipay
rm -rf $1/app/MSA-Global
rm -rf $1/app/Maps
rm -rf $1/app/MiPicks
rm -rf $1/app/MiuiAudioMonitor
rm -rf $1/app/MiuiVideoPlayer
rm -rf $1/app/Music2
rm -rf $1/app/Photos
rm -rf $1/app/TranslationService
rm -rf $1/app/Videos
rm -rf $1/app/YouDaoEngine
rm -rf $1/app/YouTube
rm -rf $1/app/facebook-appmanager
rm -rf $1/app/talkback
rm -rf $1/app/Lens
rm -rf $1/app/CatchLog
rm -rf $1/app/Joyose
rm -rf $1/app/GuardProvider
rm -rf $1/app/Zman
rm -rf $1/app/mi_connect_service
rm -rf $1/app/CtsShimPrebuilt
rm -rf $1/app/FM
rm -rf $1/app/FileExplorer_old
rm -rf $1/app/Notes
rm -rf $1/app/Netflix_activation
rm -rf $1/app/IdMipay
rm -rf $1/app/IFAAService
rm -rf $1/app/Notes
rm -rf $1/app/KeyChain
rm -rf $1/app/OTrPBroker
rm -rf $1/app/SoterService
rm -rf $1/app/Lens
rm -rf $1/app/MiuiContentCatcher
rm -rf $1/app/PacProcessor
rm -rf $1/app/Email
rm -rf $1/app/CameraTools
rm -rf $1/app/FidoAuthen
rm -rf $1/app/MiuiFrequentPhrase
rm -rf $1/app/FidoClient
rm -rf $1/app/MiDrive
rm -rf $1/app/MiuiScreenRecorder
rm -rf $1/app/MiGalleryLockscreen
rm -rf $1/app/Traceur
rm -rf $1/app/wps-lite
rm -rf $1/app/CatcherPatch
rm -rf $1/app/VsimCore
rm -rf $1/app/Protips
rm -rf $1/app/SecureElement
rm -rf $1/app/XMSFKeeper
rm -rf $1/app/CompanionDeviceManager
rm -rf $1/app/Health
rm -rf $1/app/AiAsstVision
rm -rf $1/app/TSMClient
rm -rf $1/app/XMCloudEngine
rm -rf $1/app/AutoTest
rm -rf $1/app/FM_TEST
rm -rf $1/app/MSA
rm -rf $1/app/Qmmi
rm -rf $1/app/cit
rm -rf $1/app/MiuiSuperMarket
rm -rf $1/app/VoiceTrigger
rm -rf $1/app/GFTest
rm -rf $1/app/ModemLog
rm -rf $1/app/SensorTestTool
rm -rf $1/app/CameraTest
rm -rf $1/priv-app/Backup
rm -rf $1/priv-app/Browser
rm -rf $1/priv-app/Calendar
rm -rf $1/priv-app/MiuiScanner
rm -rf $1/priv-app/Velvet
rm -rf $1/priv-app/Weather
rm -rf $1/priv-app/WeatherProvider
rm -rf $1/priv-app/MiuiVideo
rm -rf $1/priv-app/PersonalAssistant
rm -rf $1/priv-app/MiService
rm -rf $1/priv-app/Music
rm -rf $1/priv-app/Provision
rm -rf $1/priv-app/GameBoosterGlobal
rm -rf $1/priv-app/GameCenterGlobal
rm -rf $1/priv-app/GlobalUserGuide
rm -rf $1/priv-app/MiDrop
rm -rf $1/priv-app/MiuiBrowserGlobal
rm -rf $1/priv-app/PersonalAssistantGlobal
rm -rf $1/priv-app/SoundRecorder
rm -rf $1/priv-app/Turbo
rm -rf $1/priv-app/YellowPage
rm -rf $1/priv-app/facebook-installer
rm -rf $1/priv-app/facebook-services
rm -rf $1/priv-app/MiShare
rm -rf $1/priv-app/Tag
rm -rf $1/priv-app/MiuiMusicGlobal
rm -rf $1/priv-app/MiCalendarGlobal
rm -rf $1/priv-app/MiBrowserGlobal
rm -rf $1/priv-app/AuthManager
rm -rf $1/priv-app/MiuiExtraPhoto
rm -rf $1/priv-app/ONS
rm -rf $1/priv-app/StatementService
rm -rf $1/priv-app/CtsShimPrivPrebuilt
rm -rf $1/priv-app/LocalTransport
rm -rf $1/priv-app/MiMover
rm -rf $1/priv-app/QuickSearchBox
rm -rf $1/priv-app/MiRecycle
rm -rf $1/priv-app/CleanMaster
rm -rf $1/priv-app/FusedLocation
rm -rf $1/priv-app/MiuiAod
rm -rf $1/priv-app/MiGameCenterSDKService
rm -rf $1/priv-app/MiRcs
rm -rf $1/priv-app/NewHome

# Nuke MIUI useless product apks
rm -rf $1/product/app/Gmail2
rm -rf $1/product/app/GoogleTTS
rm -rf $1/product/app/Maps
rm -rf $1/product/app/YouTube
rm -rf $1/product/app/talkback
rm -rf $1/product/app/ModuleMetadataGoogle
rm -rf $1/product/app/uceShimService
rm -rf $1/product/app/CalendarGoogle
rm -rf $1/product/app/Chrome
rm -rf $1/product/app/ModuleMetadataGooglePrebuilt
rm -rf $1/product/app/GoogleOne
rm -rf $1/product/priv-app/Velvet
rm -rf $1/product/priv-app/CarrierServices
rm -rf $1/product/priv-app/AndroidAutoStub
rm -rf $1/product/priv-app/HotwordEnrollmentOKGoogleHEXAGON
rm -rf $1/product/priv-app/Turbo
rm -rf $1/product/priv-app/HotwordEnrollmentXGoogleHEXAGON
rm -rf $1/product/priv-app/GoogleAssistant
rm -rf $1/product/priv-app/GoogleFeedback
rm -rf $1/product/priv-app/QAS_DVC_MSP


app_list="InMIpay MIDrop MiLinkGlobal miPlayClient MIUIFileExplorer MIUICompass Cit MIUIHealthGlobal MiuiScanner MIUIMiPicks MIUINotes MIWallpaper MIUITouchAssistantGlobal XMSFKeepekAll DynamicSystemInstallationService MIService MIShare* MiuiCamera MIUIMusic* MIUIYellowPage* DeviceInfo DynamicDDSService dpmserviceapp EmergencyInfo GoogleFeedback seccamservice WfdService"
for app in $app_list; do
rm -rf $1/*app/$app
rm -rf $1/*/*app/$app
done

# Nuke MIUI useless product apk
rm -rf $1/priv-app/MIUIAod
rm -rf $1/priv-app/MIUIBrowser
rm -rf $1/priv-app/MIUICamera
rm -rf $1/priv-app/MIUIContentExtension
rm -rf $1/priv-app/MIUIMusic
rm -rf $1/priv-app/MIUIVideo
rm -rf $1/priv-app/MIUIGallery
rm -rf $1/priv-app/Mirror
rm -rf $1/priv-app/MIUIShare
rm -rf $1/priv-app/MIUICalendar
rm -rf $1/priv-app/MIUIYellowPage
rm -rf $1/app/MiLink
rm -rf $1/app/MILink
rm -rf $1/app/MIPay
rm -rf $1/app/mab
rm -rf $1/app/MiSound  
rm -rf $1/app/MIUIDeskClock
rm -rf $1/app/MIUIFileExplorer 
rm -rf $1/app/MIUISuperMarket 
rm -rf $1/product/data-app/*
rm -rf $1/product/media/audio/alarms/*
rm -rf $1/product/media/audio/notifications/*
rm -rf $1/product/media/audio/ringtones/*
rm -rf $1/product/app/Gmail2
rm -rf $1/product/app/GoogleTTS
rm -rf $1/product/app/Maps
rm -rf $1/product/app/YouTube
rm -rf $1/product/app/talkback
rm -rf $1/product/app/ModuleMetadataGoogle
rm -rf $1/product/app/uceShimService
rm -rf $1/product/app/CalendarGoogle
rm -rf $1/product/app/Chrome
rm -rf $1/product/app/ModuleMetadataGooglePrebuilt
rm -rf $1/product/app/GoogleOne
rm -rf $1/product/priv-app/Velvet
rm -rf $1/product/priv-app/CarrierServices
rm -rf $1/product/priv-app/AndroidAutoStub
rm -rf $1/product/priv-app/HotwordEnrollmentOKGoogleHEXAGON
rm -rf $1/product/priv-app/Turbo
rm -rf $1/product/priv-app/HotwordEnrollmentXGoogleHEXAGON
rm -rf $1/product/priv-app/GoogleAssistant
rm -rf $1/product/priv-app/GoogleFeedback
rm -rf $1/product/priv-app/QAS_DVC_MSP
rm -rf $1/app/Drive
rm -rf $1/app/Duo
rm -rf $1/app/Calculator
rm -rf $1/priv-app/Calculator
rm -rf $1/app/Maps
rm -rf $1/product/app/Chrome-Stub
rm -rf $1/product/app/Chrome
rm -rf $1/app/YouTube
rm -rf $1/app/talkback
rm -rf $1/product/app/talkback
rm -rf $1/product/app/MarkupGoogle
rm -rf $1/app/CalendarGoogle
rm -rf $1/app/Photos
rm -rf $1/app/GooglePay
rm -rf $1/app/Music2
rm -rf $1/app/CameraTest
rm -rf $1/priv-app/Turbo
rm -rf $1/app/PaymentService
rm -rf $1/app/Music
rm -rf $1/app/alphame
rm -rf $1/app/assistans
rm -rf $1/priv-app/assistans
rm -rf $1/app/suggestion
rm -rf $1/priv-app/suggestion
rm -rf $1/app/picker
rm -rf $1/priv-app/picker
rm -rf $1/app/mstore
rm -rf $1/priv-app/mstore
rm -rf $1/app/calculator
rm -rf $1/priv-app/calculator
rm -rf $1/app/callsetting
rm -rf $1/priv-app/callsetting
rm -rf $1/app/camera
rm -rf $1/priv-app/camera
rm -rf $1/app/dsgame
rm -rf $1/priv-app/dsgame
rm -rf $1/app/flymelab
rm -rf $1/priv-app/flymelab
rm -rf $1/app/filemanager
rm -rf $1/priv-app/filemanager
rm -rf $1/app/gallery
rm -rf $1/priv-app/gallery
rm -rf $1/app/gamecenter
rm -rf $1/priv-app/gamecenter
rm -rf $1/app/mznfcpay
rm -rf $1/priv-app/mznfcpay
rm -rf $1/app/notepaper
rm -rf $1/priv-app/notepaper
rm -rf $1/app/pay
rm -rf $1/app/pedometer
rm -rf $1/app/safe
rm -rf $1/priv-app/safe
rm -rf $1/app/mcare
rm -rf $1/priv-app/mcare
rm -rf $1/priv-app/pedometer
rm -rf $1/priv-app/pay
rm -rf $1/app/Gmail2
rm -rf $1/app/GoogleTTS
rm -rf $1/priv-app/Backup
rm -rf $1/priv-app/Browser
rm -rf $1/priv-app/Calendar
rm -rf $1/app/AppCenterIntl
rm -rf $1/app/Camera
rm -rf $1/app/IntlNews
rm -rf $1/app/NotePaper
rm -rf $1/app/Videos
rm -rf $1/priv-app/Email
rm -rf $1/priv-app/Music
rm -rf $1/priv-app/Search
rm -rf $1/priv-app/SoundRecorder
rm -rf $1/priv-app/ToolBox
rm -rf $1/priv-app/Velvet
rm -rf $1/priv-app/Video
rm -rf $1/priv-app/wt_logcat
rm -rf $1/app/MzUpdate*
rm -rf $1/app/Updater
rm -rf $1/MzApp/Game*
rm -rf $1/MzApp/Life
rm -rf $1/MzApp/MzStore
rm -rf $1/MzApp/Reader
rm -rf $1/MzApp/VideoClips

rm -rf $1/app/AlwaysOnDisplay
rm -rf $1/app/AppCenter
rm -rf $1/app/BasicDreams
rm -rf $1/app/Bridge
rm -rf $1/app/CosMaster
rm -rf $1/app/FileManager
rm -rf $1/app/FlymeAlarmClock
rm -rf $1/app/MzCloudService
rm -rf $1/app/MzUCService
rm -rf $1/app/MzPay
rm -rf $1/app/MzSecurity
rm -rf $1/app/MzShare
rm -rf $1/app/MzSyncService
rm -rf $1/app/Protips
rm -rf $1/MzApp/ARruler
rm -rf $1/MzApp/Calculator
rm -rf $1/MzApp/DsGame
rm -rf $1/MzApp/Email
rm -rf $1/MzApp/FlymeCalendar
rm -rf $1/MzApp/NotePaper
rm -rf $1/MzApp/Pedometer
rm -rf $1/MzApp/TodoList
rm -rf $1/MzApp/Weather
rm -rf $1/priv-app/ActivatePhone
rm -rf $1/priv-app/AlphaMe
rm -rf $1/priv-app/Assistant
rm -rf $1/priv-app/Feedback
rm -rf $1/priv-app/FlymeGallery
rm -rf $1/priv-app/FlymeMusic
rm -rf $1/priv-app/FlymeSoundRecorder
rm -rf $1/priv-app/MeizuPay
rm -rf $1/priv-app/MzSetupWizard
rm -rf $1/priv-app/Suggestion
rm -rf $1/priv-app/VoiceAssistant

rm -rf $1/customizecenter/wallpapers/2a.png
rm -rf $1/customizecenter/wallpapers/3a.png
rm -rf $1/customizecenter/wallpapers/4a.png
rm -rf $1/customizecenter/wallpapers/5a.png
rm -rf $1/customizecenter/wallpapers/2a_thumb.png
rm -rf $1/customizecenter/wallpapers/3a_thumb.png
rm -rf $1/customizecenter/wallpapers/4a_thumb.png
rm -rf $1/customizecenter/wallpapers/5a_thumb.png
rm -rf $1/customizecenter/wallpapers/a.jpg
rm -rf $1/customizecenter/wallpapers/a_thumb.jpg
rm -rf $1/customizecenter/wallpapers/bb.jpg
rm -rf $1/customizecenter/wallpapers/bb_thumb.jpg
rm -rf $1/customizecenter/wallpapers/b.jpg
rm -rf $1/customizecenter/wallpapers/b_thumb.jpg
rm -rf $1/customizecenter/wallpapers/eee.jpg
rm -rf $1/customizecenter/wallpapers/eee_thumb.jpg
rm -rf $1/customizecenter/wallpapers/ee.jpg
rm -rf $1/customizecenter/wallpapers/ee_thumb.jpg
rm -rf $1/customizecenter/wallpapers/e.png
rm -rf $1/customizecenter/wallpapers/e_thumb.jpg
rm -rf $1/customizecenter/wallpapers/fff.jpg 
rm -rf $1/customizecenter/wallpapers/fff_thumb.jpg
rm -rf $1/customizecenter/wallpapers/ff.jpg
rm -rf $1/customizecenter/wallpapers/ff_thumb.jpg
rm -rf $1/customizecenter/wallpapers/f.png
rm -rf $1/customizecenter/wallpapers/f_thumb.jpg
rm -rf $1/customizecenter/wallpapers/ggg.jpg 
rm -rf $1/customizecenter/wallpapers/ggg_thumb.jpg
rm -rf $1/customizecenter/wallpapers/gg.jpg
rm -rf $1/customizecenter/wallpapers/gg_thumb.jpg
rm -rf $1/customizecenter/wallpapers/g.png
rm -rf $1/customizecenter/wallpapers/g_thumb.jpg
rm -rf $1/customizecenter/wallpapers/h.png
rm -rf $1/customizecenter/wallpapers/h_thumb.png
rm -rf $1/customizecenter/wallpapers/i.png
rm -rf $1/customizecenter/wallpapers/i_thumb.png
rm -rf $1/customizecenter/wallpapers/j.png
rm -rf $1/customizecenter/wallpapers/j_thumb.png
rm -rf $1/customizecenter/wallpapers/k.png
rm -rf $1/customizecenter/wallpapers/k_thumb.png
rm -rf $1/customizecenter/wallpapers/l.png
rm -rf $1/customizecenter/wallpapers/l_thumb.png
rm -rf $1/customizecenter/wallpapers/m.png
rm -rf $1/customizecenter/wallpapers/m_thumb.png
rm -rf $1/customizecenter/wallpapers/o.png
rm -rf $1/customizecenter/wallpapers/o_thumb.png
rm -rf $1/customizecenter/wallpapers/p.png
rm -rf $1/customizecenter/wallpapers/p_thumb.png
rm -rf $1/customizecenter/wallpapers/q.png
rm -rf $1/customizecenter/wallpapers/q_thumb.png
rm -rf $1/customizecenter/wallpapers/r.png
rm -rf $1/customizecenter/wallpapers/r_thumb.png

rm -rf $1/../res
rm -rf $1/reserve/*

# Nuke OnePlus useless app apks
rm -rf $1/app/GooglePay
rm -rf $1/app/Netflix_Activation
rm -rf $1/app/Netflix_Stub
rm -rf $1/app/OPYellowpage
rm -rf $1/app/OPWallpaperResources
rm -rf $1/app/OEMLogKit
rm -rf $1/app/OPBackup
rm -rf $1/app/QQBrowser
rm -rf $1/app/ARCore_stub
rm -rf $1/app/AntHalService
rm -rf $1/app/Calculator
rm -rf $1/app/CtsShimPrebuilt
rm -rf $1/app/EngineeringMode
rm -rf $1/app/EngSpecialTest
rm -rf $1/app/OPBreathMode
rm -rf $1/app/OPPush
rm -rf $1/app/OsuLogin
rm -rf $1/app/PhotosOnline
rm -rf $1/app/Rftoolkit
rm -rf $1/app/oem_tcma
rm -rf $1/app/aptxals
rm -rf $1/app/LogKitSdService
rm -rf $1/app/OPBugReportLite
rm -rf $1/app/OPCommonLogTool
rm -rf $1/app/OPIntelliService
rm -rf $1/app/OPTelephonyDiagnoseManager
rm -rf $1/app/OemAutoTestServer
rm -rf $1/app/OpLogkit
rm -rf $1/app/SmscPlugger
rm -rf $1/app/OPInstantTranslation
rm -rf $1/app/Calendar
rm -rf $1/app/Exchange2
rm -rf $1/app/NFCTestMode
rm -rf $1/app/NxpNfcNci
rm -rf $1/app/NxpSecureElement
rm -rf $1/app/OPFindMyPhoneUtils
rm -rf $1/app/OposAds
rm -rf $1/app/QColor
rm -rf $1/app/SensorTestTool
rm -rf $1/app/SoterService
rm -rf $1/app/SoundRecorder
rm -rf $1/app/nearme
rm -rf $1/app/heytap_mcs_cn
rm -rf $1/app/WifiRfTestApk
rm -rf $1/app/baidushurufa
rm -rf $1/app/ARCore_stub
rm -rf $1/app/CompanionDeviceManager
rm -rf $1/app/aptxals
rm -rf $1/app/aptxui
rm -rf $1/priv-app/OnePlusCamera
rm -rf $1/priv-app/OnePlusGallery
rm -rf $1/priv-app/Velvet
rm -rf $1/priv-app/CtsShimPrivPrebuilt
rm -rf $1/priv-app/HotwordEnrollmentXGoogleWCD9340
rm -rf $1/priv-app/HotwordEnrollmentOKGoogleWCD9340
rm -rf $1/priv-app/subsdm
rm -rf $1/priv-app/TSDM
rm -rf $1/priv-app/TagGoogle
rm -rf $1/priv-app/ONS
rm -rf $1/priv-app/LocalTransport
rm -rf $1/priv-app/Houston
rm -rf $1/priv-app/OPAppCategoryProvider
rm -rf $1/priv-app/OPDeviceManager
rm -rf $1/priv-app/OPDeviceManagerProvider
rm -rf $1/priv-app/AutoNaviNLP
rm -rf $1/priv-app/BlockedNumberProvider
rm -rf $1/priv-app/CallLogBackup
rm -rf $1/priv-app/EmergencyInfo
rm -rf $1/priv-app/FusedLocation
rm -rf $1/priv-app/IFAAService
rm -rf $1/priv-app/NearmeBrowser
rm -rf $1/priv-app/OPFindMyPhone
rm -rf $1/priv-app/OPMarket
rm -rf $1/priv-app/OPVoiceAssistant
rm -rf $1/priv-app/OPVoiceWakeUp
rm -rf $1/priv-app/Tag
rm -rf $1/priv-app/StatementService
rm -rf $1/priv-app/Wallet
rm -rf $1/priv-app/BuiltInPrintService
rm -rf $1/priv-app/RcsSDK
rm -rf $1/priv-app/Shell
rm -rf $1/priv-app/ProxyHandler

# Nuke OnePlus useless product apks
rm -rf $1/product/app/TmoEngMode
rm -rf $1/product/app/embms
rm -rf $1/product/app/ModuleMetadataGooglePrebuilt
rm -rf $1/product/app/colorservice
rm -rf $1/product/app/DeviceInfo
rm -rf $1/product/app/QdcmFF
rm -rf $1/product/app/talkback
rm -rf $1/product/app/Chrome
rm -rf $1/product/app/GoogleAssistant
rm -rf $1/product/app/GoogleTTS
rm -rf $1/product/app/Photos
rm -rf $1/product/app/com.google.mainline.telemetry
rm -rf $1/product/app/Calculator
rm -rf $1/product/app/Drive
rm -rf $1/product/app/YTMusic
rm -rf $1/product/app/CalendarGoogle
rm -rf $1/product/app/Duo
rm -rf $1/product/app/Maps
rm -rf $1/product/app/TrichromeLibrary
rm -rf $1/product/app/YouTube
rm -rf $1/product/app/Gmail2
rm -rf $1/product/app/GooglePay
rm -rf $1/product/app/Videos
rm -rf $1/product/app/com.google.android.modulemetadata
rm -rf $1/product/app/Music2
rm -rf $1/product/priv-app/AndroidAutoStub
rm -rf $1/product/priv-app/GoogleFeedback
rm -rf $1/product/priv-app/LiveCaption
rm -rf $1/product/priv-app/QAS_DVC_MSP
rm -rf $1/product/priv-app/Velvet
rm -rf $1/product/priv-app/HotwordEnrollmentXGoogleHEXAGON
rm -rf $1/product/priv-app/OobConfig
rm -rf $1/product/priv-app/Turbo
rm -rf $1/product/priv-app/HotwordEnrollmentOKGoogleHEXAGON

# Nuke OnePlus useless india apks
rm -rf $1/india/app/HeytapIdProvider
rm -rf $1/india/app/Nearme
rm -rf $1/india/app/OPMemberShip
rm -rf $1/india/app/OPSilentInstaller
rm -rf $1/india/app/heytap_mcs_in
rm -rf $1/india/priv-app/CloudService
rm -rf $1/india/priv-app/IndiaOPRoamingServiceRelease
rm -rf $1/india/priv-app/OPWorkLifeBalance
rm -rf $1/india/reserve/EpicGameApp
rm -rf $1/india/reserve/IndiaOPRoamingAppRelease
rm -rf $1/india/reserve/OPNote

#Nuke Nubia
rm -rf $1/app/HarassIntercept*
rm -rf $1/app/Jobdispatcer*
rm -rf $1/app/LeagueShare*
rm -rf $1/app/NB*
rm -rf $1/app/NubiaAfterSale*
rm -rf $1/app/NubiaFan
rm -rf $1/app/NubiaPush*
rm -rf $1/app/NubiaG*
rm -rf $1/app/NubiaShare*
rm -rf $1/app/*_nubia*
rm -rf $1/app/Woodpecker*
rm -rf $1/*app/*LiveWallpaper*
rm -rf $1/*app/*eibo*
rm -rf $1/app/ZDoubleApp*
rm -rf $1/app/*DynamicWallpaper*
rm -rf $1/app/*Game*
rm -rf $1/app/*NBSecurity*
rm -rf $1/app/nubia_NeoQuick*
rm -rf $1/*app/*account*
rm -rf $1/app/redtea*
rm -rf $1/fonts/NotoSans*
rm -rf $1/fonts/NotoSerif*
rm -rf $1/media/*/*nubia*
rm -rf $1/app/wallpaper/1920*
rm -rf $1/app/wallpaper/middle*
rm -rf $1/*app/*Game*
rm -rf $1/*app/*Emergency*
rm -rf $1/*app/*Tencent*
rm -rf $1/*/*app/*Tencent*
rm -rf $1/priv-app/ZNubia*
rm -rf $1/priv-app/*Theme*
rm -rf $1/*/*app/*Appstore*
rm -rf $1/*/*app/*Usercenter*
rm -rf $1/*/media/*theme*/*colorful*
rm -rf $1/*/media/*theme*/*tech*
rm -rf $1/*/media/*theme*/*pubg*
rm -rf $1/*/media/*theme*/*machao*
rm -rf $1/*/media/*theme*/*wzry*
rm -rf $1/product/media/audio/alarms/*
rm -rf $1/product/media/audio/notifications/*
rm -rf $1/product/media/audio/ringtones/*