#!/bin/bash

LOCALDIR=`cd "$( dirname ${BASH_SOURCE[0]} )" && pwd`
cd $LOCALDIR

systemdir=$1
rm -rf $1/fonts/D*
rm -rf $1/fonts/Source*
rm -rf $1/fonts/NotoSans*
rm -rf $1/fonts/NotoSerif*
rm -rf $1/*/*app/*Recorder*
rm -rf $1/*app/*Recorder*
rm -rf $1/*app/Compass
rm -rf $1/*app/*Warranty*
rm -rf $1/*/*app/*Map*
rm -rf $1/*app/*Map*
rm -rf $1/*/*app/*acebook*
rm -rf $1/*app/*acebook*
rm -rf $1/*/*app/*YouTube*
rm -rf $1/*app/*YouTube*
rm -rf $1/*/*app/*Velvet*
rm -rf $1/*/*app/*PixelWall*
rm -rf $1/*/*app/*DevicePersonalization*
rm -rf $1/*/*app/*Duo*
rm -rf $1/*app/*Pay*
rm -rf $1/*app/*Market*
rm -rf $1/*/*app/*Market*
rm -rf $1/*/*app/*Pay*
rm -rf $1/*/*app/*Gmail*
rm -rf $1/*app/*Velvet*
rm -rf $1/*/preset_apps/*
rm -rf $1/*/data-app/*
rm -rf $1/reserve/*
rm -rf $1/preload/*
rm -rf $1/*/preload/*
rm -rf $1/preset_apps/*
rm -rf $1/data-app/*
rm -rf $1/*/*app/*FM*
rm -rf $1/*app/*FM*
rm -rf $1/*/*app/*Browser*
rm -rf $1/*app/*Browser*
rm -rf $1/*/*app/*Photos*
rm -rf $1/*/*app/*Keep*
rm -rf $1/*/*app/*Tips*
rm -rf $1/*/*app/*Music*
rm -rf $1/*/*app/*DevicePolicy*
rm -rf $1/*/*app/*arcore*
rm -rf $1/*/*app/*AndroidAuto*
rm -rf $1/*/*app/*Verizon*
rm -rf $1/*/*app/*LiveWallpaper*
rm -rf $1/*/*app/Scribe*
rm -rf $1/*/*app/*Calendar*
rm -rf $1/*/*app/*Chrome*
rm -rf $1/*/*app/Drive
rm -rf $1/*/*app/GoogleOne*
rm -rf $1/*/*app/GoogleAssist*
rm -rf $1/*/*app/*Bugle*
rm -rf $1/*/*app/*Tycho*
rm -rf $1/*/*app/*talkback*
rm -rf $1/*/*app/*Maestro*
rm -rf $1/*app/*UserCent*
rm -rf $1/*app/*account*
rm -rf $1/*/*app/*OTA*
rm -rf $1/*app/*OTA*
rm -rf $1/*app/*ppstore*
rm -rf $1/*/*app/*ppstore*
rm -rf $1/apex/*vndk.v28*
rm -rf $1/system_ext/apex/*vndk.v28*
rm -rf $1/app/AIEngine
rm -rf $1/app/APrintSpooler
rm -rf $1/app/ARCoreStub0
rm -rf $1/app/BBKCrontab
rm -rf $1/app/BBKFMRadio
rm -rf $1/app/BBKLOG
rm -rf $1/app/BBKMusic
rm -rf $1/app/BBKNotes
rm -rf $1/app/BBKSoundRecorder
rm -rf $1/app/BBKPhoneInstructions
rm -rf $1/app/BSPTest
rm -rf $1/app/Calculator
rm -rf $1/app/Compass
rm -rf $1/app/CustomTool
rm -rf $1/app/EngineerCamera
rm -rf $1/app/EPM
rm -rf $1/app/EWarranty
rm -rf $1/app/Feedback
rm -rf $1/app/FingerprintEngineer
rm -rf $1/app/FloatingCloud
rm -rf $1/app/Ft*36
rm -rf $1/app/GameCube
rm -rf $1/app/GameWatch
rm -rf $1/app/GlobalSearch
rm -rf $1/app/GmailProvider
rm -rf $1/app/NetworkImprove
rm -rf $1/app/Nvt*81
rm -rf $1/app/Plant
rm -rf $1/app/LogSystem
rm -rf $1/app/PlayAutoInstallStub
rm -rf $1/app/VideoEditor
rm -rf $1/app/VideoPlayer
rm -rf $1/app/VLife_vivo
rm -rf $1/app/VivoAssistant
rm -rf $1/app/VivoCamera
rm -rf $1/app/VivoGallery
rm -rf $1/app/VivoPushEngine
rm -rf $1/app/VivoSmartNip
rm -rf $1/app/VivoTips
rm -rf $1/app/VivoTws
rm -rf $1/app/VivoUnionPayEx
rm -rf $1/app/VivoWebsite
rm -rf $1/app/vivoDemoVideo
rm -rf $1/app/vivoEngineerMode
rm -rf $1/app/vivogame
rm -rf $1/app/vivoScan
rm -rf $1/app/WifiEngineerMode
rm -rf $1/app/YandexActive
rm -rf $1/priv-app/LocalTransport
rm -rf $1/priv-app/ONS
rm -rf $1/priv-app/Omacp
rm -rf $1/priv-app/VivoBrowser
rm -rf $1/priv-app/VivoOffice
rm -rf $1/product/priv-app/SearchSelector

# Remove facebook apks
rm -rf $1/app/facebook-appmanager
rm -rf $1/priv-app/facebook-installer
rm -rf $1/priv-app/facebook-services

# Remove GApps apks
rm -rf $1/app/GoogleLens
rm -rf $1/app/GoogleLensTier
rm -rf $1/product/app/CalendarGoogle
rm -rf $1/product/app/GoogleContacts
rm -rf $1/product/app/Duo
rm -rf $1/product/app/Gmail2
rm -rf $1/product/app/GoogleAssistant
rm -rf $1/product/app/GooglePay
rm -rf $1/product/app/GoogleTTS
rm -rf $1/product/app/Keep
rm -rf $1/product/app/Maps
rm -rf $1/product/app/Photos
rm -rf $1/product/app/YTMusic
rm -rf $1/product/app/Tycho
rm -rf $1/product/priv-app/Tycho
rm -rf $1/product/app/YouTube
rm -rf $1/product/app/talkback
rm -rf $1/product/priv-app/YouTube
rm -rf $1/product/app/YouTubeMusicPrebuilt
rm -rf $1/product/app/PrebuiltGmail
rm -rf $1/product/app/PrebuiltBugle
rm -rf $1/product/priv-app/PrebuiltBugle
rm -rf $1/product/app/Drive
rm -rf $1/product/app/DiagnosticsToolPrebuilt
rm -rf $1/product/app/Chrome
rm -rf $1/product/app/Chrome-Stub
rm -rf $1/product/app/CalendarGooglePrebuilt
rm -rf $1/product/app/NgaResources
rm -rf $1/product/priv-app/BetaFeedback
rm -rf $1/product/priv-app/DevicePersonalizationPrebuiltPixel2020
rm -rf $1/product/priv-app/HelpRtcPrebuilt
rm -rf $1/product/priv-app/MyVerizonServices
rm -rf $1/product/priv-app/OTAConfigPrebuilt
rm -rf $1/product/priv-app/PixelLiveWallpaperPrebuilt
rm -rf $1/product/priv-app/RecorderPrebuilt
rm -rf $1/product/priv-app/SafetyHubPrebuilt
rm -rf $1/product/priv-app/ScribePrebuilt
rm -rf $1/app/datastatusnotification
rm -rf $1/app/QAS_DVC_MSP_VZW
rm -rf $1/app/VZWAPNLib
rm -rf $1/app/vzw_msdc_api
rm -rf $1/priv-app/CNEService
rm -rf $1/priv-app/DMService
rm -rf $1/priv-app/VzwOmaTrigger
rm -rf $1/priv-app/qcrilmsgtunnel
rm -rf $1/product/priv-app/ConnMO
rm -rf $1/product/priv-app/DCMO
rm -rf $1/product/priv-app/MyVerizonServices
rm -rf $1/product/priv-app/SprintDM
rm -rf $1/product/priv-app/SprintHM
rm -rf $1/product_services/priv-app/PrebuiltGmsCorePi/app_chimera
rm -rf $1/product/priv-app/PrebuiltGmsCoreQt/app_chimera
rm -rf $1/product/priv-app/PrebuiltGmsCore/app_chimera
rm -rf $1/etc/permissions/com.google.android.camera.experimental2017.xml
rm -rf $1/product/app/GoogleCamera
rm -rf $1/product/app/WallpapersBReel*
rm -rf $1/product/priv-app/EuiccSupportPixel
rm -rf $1/product/priv-app/EuiccGoogle
rm -rf $1/product/priv-app/WfcActivation
rm -rf $1/product/app/AndroidAutoStubPrebuilt
rm -rf $1/product/priv-app/AndroidAutoStubPrebuilt
rm -rf $1/product/app/arcore
rm -rf $1/product/app/DevicePolicyPrebuilt
rm -rf $1/product/app/GoogleTTS
rm -rf $1/product/app/MarkupGoogle
rm -rf $1/product/priv-app/TurboPrebuilt
rm -rf $1/product/priv-app/TipsPrebuilt
rm -rf $1/product/priv-app/Velvet
rm -rf $1/product/app/Velvet

# Fix Files-DocumentsUI
rm -rf $1/product/overlay/PixelDocumentsUIOverlay

# Some Unused Google Apps
rm -rf $1/product/app/Music2
rm -rf $1/product/app/Photos
rm -rf $1/product/app/Videos
rm -rf $1/system_ext/priv-app/HbmSVManager
rm -rf $1/system_ext/priv-app/MyVerizonServices
rm -rf $1/system_ext/priv-app/OBDM_Permissions
rm -rf $1/system_ext/priv-app/obdm_stub

rm -rf $1/preload/*
rm -rf $1/app/AR*
rm -rf $1/app/BackupRestore*
rm -rf $1/app/BTtestmode
rm -rf $1/app/Calculator2
rm -rf $1/app/ChildrenSpace
rm -rf $1/app/EmailPartnerProvider
rm -rf $1/app/FindMyPhoneClient
rm -rf $1/app/Gamecenter
rm -rf $1/app/Ocrscanner
rm -rf $1/app/Oshare
rm -rf $1/app/OV*
rm -rf $1/app/com.*
rm -rf $1/app/OTA*
rm -rf $1/app/Health*
rm -rf $1/app/ModemTestMode
rm -rf $1/app/NewSoundRecorder
rm -rf $1/app/talkback
rm -rf $1/app/FM2
rm -rf $1/app/Maps
rm -rf $1/app/Keep
rm -rf $1/app/Gmail2
rm -rf $1/app/GoogleTTS
rm -rf $1/app/NewSoundRecorder
rm -rf $1/app/OppoCamera
rm -rf $1/app/OppoCompass2
rm -rf $1/app/OppoDCS
rm -rf $1/app/Youtube
rm -rf $1/app/SecurePay
rm -rf $1/app/SecureElement
rm -rf $1/app/SafeCenter
rm -rf $1/priv-app/BlackList
rm -rf $1/priv-app/BlackListApp
rm -rf $1/priv-app/Browser
rm -rf $1/priv-app/com.*
rm -rf $1/priv-app/sg.*
rm -rf $1/priv-app/Tag*
rm -rf $1/priv-app/NewSoundRecorder
rm -rf $1/priv-app/SOS*
rm -rf $1/priv-app/deezer*
rm -rf $1/priv-app/TestApp5G
rm -rf $1/priv-app/com.facebook.system
rm -rf $1/priv-app/SmartDrive
rm -rf $1/priv-app/OppoMusic
rm -rf $1/priv-app/OppoBootReg
rm -rf $1/priv-app/OppoGallery2
rm -rf $1/priv-app/VideoGallery
rm -rf $1/priv-app/Velvet
rm -rf $1/priv-app/VideoGallery
rm -rf $1/reserve
rm -rf $1/app/com.amazon.appmanager
rm -rf $1/app/com.facebook.appmanager
rm -rf $1/app/KeKeMarket
rm -rf $1/app/KeKePay
rm -rf $1/app/KeKeUserCenter
rm -rf $1/priv-app/KeKeMarket
rm -rf $1/priv-app/KeKePay
rm -rf $1/priv-app/KeKeUserCenter
rm -rf $1/app/NXPNfcNci
rm -rf $1/app/OcrScanner
rm -rf $1/app/OcrService
rm -rf $1/product/app/Chrome
rm -rf $1/product/app/Keep
rm -rf $1/product/app/Maps
rm -rf $1/product/app/YouTube
rm -rf $1/product/app/Velvet
rm -rf $1/product/app/GoogleFeedback
rm -rf $1/product/app/GoogleTTS
rm -rf $1/product/app/Gmail2
rm -rf $1/product/priv-app/Chrome
rm -rf $1/product/priv-app/Keep
rm -rf $1/product/priv-app/Maps
rm -rf $1/product/priv-app/YouTube
rm -rf $1/product/priv-app/Velvet
rm -rf $1/product/priv-app/GoogleFeedback
rm -rf $1/product/priv-app/GoogleTTS
rm -rf $1/product/priv-app/Gmail2
rm -rf $1/product/priv-app/AndroidAuto*
rm -rf $1/preset_apps/*
# Drop useless apks
rm -rf $1/app/AutoAgingTest
rm -rf $1/app/DTSXULTRA
rm -rf $1/app/FactoryTestAdvanced
rm -rf $1/app/GoodixTest
rm -rf $1/app/NBVirtualGameHandle
rm -rf $1/app/NubiaFastPair
rm -rf $1/app/Stk
rm -rf $1/app/SystemUpdate_v1.1
rm -rf $1/app/TP_YulorePage_v1.0.0
rm -rf $1/app/ZNubiaEdge
rm -rf $1/app/nubia_Browser
rm -rf $1/app/nubia_Calendar_v1.0
rm -rf $1/app/nubia_DeskClock_NX*
rm -rf $1/app/nubia_DynamicWallpaper_651
rm -rf $1/app/nubia_GameHelperModule
rm -rf $1/app/nubia_GameHighlights
rm -rf $1/app/nubia_GameLauncher
rm -rf $1/app/nubia_NeoHybrid
rm -rf $1/app/nubia_PhoneManualIntegrate
rm -rf $1/app/nubia_neoPay
rm -rf $1/priv-app/AOD_v*.*_*-release
rm -rf $1/priv-app/Camera
rm -rf $1/priv-app/NBGalleryLockScreen
rm -rf $1/priv-app/NubiaGallery
rm -rf $1/priv-app/NubiaVideo
rm -rf $1/priv-app/PhotoEditor
rm -rf $1/priv-app/ZQuickSearchBox
rm -rf $1/priv-app/nubia_HaloVoice
rm -rf $1/priv-app/nubia_touping
rm -rf $1/product/priv-app/ConfigUpdater
rm -rf $1/product/priv-app/GooglePlayServicesUpdater
rm -rf $1/system_ext/app/QCC/
rm -rf $1/data-app/*
# Nuke MIUI useless system apks
rm -rf $1/app/cit
rm -rf $1/app/MiuiCompass
rm -rf $1/app/MiuiVideoGlobal
rm -rf $1/app/PaymentService
rm -rf $1/app/Calculator
rm -rf $1/app/VoiceAssist
rm -rf $1/app/MiRadio
rm -rf $1/app/Mipay
rm -rf $1/app/NextPay
rm -rf $1/app/com.miui.qr
rm -rf $1/app/MiuiBugReport
rm -rf $1/app/AnalyticsCore
rm -rf $1/app/BasicDreams
rm -rf $1/app/BugReport
rm -rf $1/app/Drive
rm -rf $1/app/Duo
rm -rf $1/app/Gmail2
rm -rf $1/app/HybridAccessory
rm -rf $1/app/HybridPlatform
rm -rf $1/app/InMipay
rm -rf $1/app/MSA-Global
rm -rf $1/app/Maps
rm -rf $1/app/MiPicks
rm -rf $1/app/MiuiAudioMonitor
rm -rf $1/app/MiuiVideoPlayer
rm -rf $1/app/Music2
rm -rf $1/app/Photos
rm -rf $1/app/TranslationService
rm -rf $1/app/Videos
rm -rf $1/app/YouDaoEngine
rm -rf $1/app/YouTube
rm -rf $1/app/XiaomiServiceFramework
rm -rf $1/app/facebook-appmanager
rm -rf $1/app/talkback
rm -rf $1/app/Lens
rm -rf $1/app/CatchLog
rm -rf $1/app/Joyose
rm -rf $1/app/GuardProvider
rm -rf $1/app/Zman
rm -rf $1/app/mi_connect_service
rm -rf $1/app/CtsShimPrebuilt
rm -rf $1/app/FM
rm -rf $1/app/FileExplorer_old
rm -rf $1/app/Notes
rm -rf $1/app/Netflix_activation
rm -rf $1/app/IdMipay
rm -rf $1/app/IFAAService
rm -rf $1/app/Notes
rm -rf $1/app/XiaomiSimActivateService
rm -rf $1/app/KeyChain
rm -rf $1/app/OTrPBroker
rm -rf $1/app/SoterService
rm -rf $1/app/Lens
rm -rf $1/app/MiuiContentCatcher
rm -rf $1/app/PacProcessor
rm -rf $1/app/Email
rm -rf $1/app/CameraTools
rm -rf $1/app/FidoAuthen
rm -rf $1/app/MiuiFrequentPhrase
rm -rf $1/app/FidoClient
rm -rf $1/app/MiDrive
rm -rf $1/app/MiuiScreenRecorder
rm -rf $1/app/MiGalleryLockscreen
rm -rf $1/app/Traceur
rm -rf $1/app/wps-lite
rm -rf $1/app/CatcherPatch
rm -rf $1/app/VsimCore
rm -rf $1/app/Protips
rm -rf $1/app/SecureElement
rm -rf $1/app/XMSFKeeper
rm -rf $1/app/CompanionDeviceManager
rm -rf $1/app/Health
rm -rf $1/app/AiAsstVision
rm -rf $1/app/TSMClient
rm -rf $1/app/XMCloudEngine
rm -rf $1/app/AutoTest
rm -rf $1/app/FM_TEST
rm -rf $1/app/MSA
rm -rf $1/app/Qmmi
rm -rf $1/app/cit
rm -rf $1/app/MiuiSuperMarket
rm -rf $1/app/VoiceTrigger
rm -rf $1/app/GFTest
rm -rf $1/app/ModemLog
rm -rf $1/app/SensorTestTool
rm -rf $1/app/CameraTest
rm -rf $1/priv-app/Backup
rm -rf $1/priv-app/Browser
rm -rf $1/priv-app/Calendar
rm -rf $1/priv-app/MiuiScanner
rm -rf $1/priv-app/Velvet
rm -rf $1/priv-app/Weather
rm -rf $1/priv-app/WeatherProvider
rm -rf $1/priv-app/MiuiVideo
rm -rf $1/priv-app/PersonalAssistant
rm -rf $1/priv-app/MiService
rm -rf $1/priv-app/Music
rm -rf $1/priv-app/Provision
rm -rf $1/priv-app/GameBoosterGlobal
rm -rf $1/priv-app/GameCenterGlobal
rm -rf $1/priv-app/GlobalUserGuide
rm -rf $1/priv-app/MiDrop
rm -rf $1/priv-app/MiuiBrowserGlobal
rm -rf $1/priv-app/PersonalAssistantGlobal
rm -rf $1/priv-app/SoundRecorder
rm -rf $1/priv-app/Turbo
rm -rf $1/priv-app/YellowPage
rm -rf $1/priv-app/facebook-installer
rm -rf $1/priv-app/facebook-services
rm -rf $1/priv-app/MiShare
rm -rf $1/priv-app/Tag
rm -rf $1/priv-app/MiuiMusicGlobal
rm -rf $1/priv-app/MiCalendarGlobal
rm -rf $1/priv-app/MiBrowserGlobal
rm -rf $1/priv-app/AuthManager
rm -rf $1/priv-app/MiuiExtraPhoto
rm -rf $1/priv-app/ONS
rm -rf $1/priv-app/StatementService
rm -rf $1/priv-app/CtsShimPrivPrebuilt
rm -rf $1/priv-app/LocalTransport
rm -rf $1/priv-app/MiMover
rm -rf $1/priv-app/QuickSearchBox
rm -rf $1/priv-app/MiRecycle
rm -rf $1/priv-app/CleanMaster
rm -rf $1/priv-app/FusedLocation
rm -rf $1/priv-app/MiuiAod
rm -rf $1/priv-app/MiGameCenterSDKService
rm -rf $1/priv-app/MiRcs
rm -rf $1/priv-app/NewHome
